#!/usr/bin/env python3
"""---
_genealogy:
  injected_at: '2026-04-14T21:06:00.000000'
  injected_by: NC-SCR-FR-075-genealogy-injector.py
  version: '1.0'
topology: neocortex-other
level: 0
tags:
  - neocortex-other
  - level-0
  - python
  - compression
  - symbolic
  - token-optimization
---
Symbolic Compressor - Token reduction via Greek/Unicode symbol mapping.

Provides text compression using the symbolic_map.json to replace frequent terms
with single-character symbols, drastically reducing token counts for LLM context.
"""

import json
import logging
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Default path to symbolic map
DEFAULT_SYMBOLIC_MAP_PATH = (
    Path(__file__).parent.parent.parent
    / "DIR-DOC-FR-001-docs-main"
    / "symbolic_map.json"
)


class SymbolicCompressor:
    """
    Compresses text by replacing known terms with single-character symbols.

    Uses the symbolic_map.json generated by NC-SCR-FR-021-lexicon-extractor.py
    to map common NeoCortex terms to Greek letters and Unicode symbols.

    Example:
        "neocortex_agent.validate_access"  "." (if mapped)
    """

    def __init__(self, symbol_map_path: Optional[Path] = None):
        """
        Initialize compressor with symbol map.

        Args:
            symbol_map_path: Path to symbolic_map.json. If None, uses default.
        """
        self.symbol_map_path = symbol_map_path or DEFAULT_SYMBOLIC_MAP_PATH
        self.encode_map: Dict[str, str] = {}
        self.decode_map: Dict[str, str] = {}
        self.term_patterns: List[Tuple[str, str]] = []  # (pattern, symbol)
        self._load_symbol_map()

    def _load_symbol_map(self) -> None:
        """Load and prepare symbol map for efficient encoding/decoding."""
        if not self.symbol_map_path.exists():
            logger.warning(f"Symbolic map not found at {self.symbol_map_path}")
            return

        try:
            with open(self.symbol_map_path, "r", encoding="utf-8") as f:
                data = json.load(f)

            self.encode_map = data.get("encode", {})
            self.decode_map = data.get("decode", {})

            # Prepare patterns for encoding: sort terms by length (longest first)
            # to avoid partial replacements (e.g., "agent" inside "neocortex_agent")
            sorted_terms = sorted(self.encode_map.keys(), key=len, reverse=True)

            for term in sorted_terms:
                symbol = self.encode_map[term]
                # Escape special regex characters in term
                escaped_term = re.escape(term)
                # Use word boundaries for whole word matching
                # But be careful with terms containing dots, underscores
                if term.isalnum() or "_" in term:
                    pattern = r"\b" + escaped_term + r"\b"
                else:
                    pattern = escaped_term

                self.term_patterns.append((pattern, symbol))

            logger.info(
                f"Loaded symbolic map with {len(self.encode_map)} terms, {len(self.term_patterns)} patterns"
            )

        except Exception as e:
            logger.error(f"Failed to load symbolic map: {e}")

    def encode(self, text: str, aggressive: bool = False) -> str:
        """
        Encode text by replacing terms with symbols.

        Args:
            text: Input text to compress
            aggressive: If True, replace all occurrences without word boundaries
                      (faster but may cause unwanted substitutions)

        Returns:
            Encoded text with symbols
        """
        if not self.term_patterns:
            return text

        result = text

        if aggressive:
            # Simple replace for speed (may cause unwanted substitutions)
            for term, symbol in self.encode_map.items():
                result = result.replace(term, symbol)
        else:
            # Pattern-based replacement with word boundaries
            for pattern, symbol in self.term_patterns:
                result = re.sub(pattern, symbol, result)

        return result

    def decode(self, encoded_text: str) -> str:
        """
        Decode text by replacing symbols with original terms.

        Args:
            encoded_text: Text with symbols

        Returns:
            Decoded text with original terms
        """
        if not self.decode_map:
            return encoded_text

        result = encoded_text

        # For decoding, we need to replace symbols back to terms
        # Sort symbols by length (longest first) for safety
        sorted_symbols = sorted(self.decode_map.keys(), key=len, reverse=True)

        for symbol in sorted_symbols:
            term = self.decode_map[symbol]
            result = result.replace(symbol, term)

        return result

    def encode_with_stats(
        self, text: str, aggressive: bool = False
    ) -> Tuple[str, Dict[str, int]]:
        """
        Encode text and return compression statistics.

        Args:
            text: Input text
            aggressive: Aggressive encoding mode

        Returns:
            Tuple of (encoded_text, stats_dict)
        """
        original_len = len(text)
        original_tokens = self._estimate_tokens(text)

        encoded = self.encode(text, aggressive)

        encoded_len = len(encoded)
        encoded_tokens = self._estimate_tokens(encoded)

        stats = {
            "original_chars": original_len,
            "encoded_chars": encoded_len,
            "chars_saved": original_len - encoded_len,
            "chars_reduction_pct": round((1 - encoded_len / original_len) * 100, 2)
            if original_len > 0
            else 0,
            "original_tokens": original_tokens,
            "encoded_tokens": encoded_tokens,
            "tokens_saved": original_tokens - encoded_tokens,
            "tokens_reduction_pct": round(
                (1 - encoded_tokens / original_tokens) * 100, 2
            )
            if original_tokens > 0
            else 0,
            "terms_replaced": self._count_replacements(text, encoded),
        }

        return encoded, stats

    def _estimate_tokens(self, text: str) -> int:
        """
        Rough token estimation (4 chars per token average).

        Args:
            text: Text to estimate

        Returns:
            Estimated token count
        """
        return len(text) // 4

    def _count_replacements(self, original: str, encoded: str) -> int:
        """
        Count how many terms were replaced.

        Args:
            original: Original text
            encoded: Encoded text

        Returns:
            Number of replacements made
        """
        count = 0
        for term, symbol in self.encode_map.items():
            count_original = original.count(term)
            count_encoded = encoded.count(symbol)
            if count_original > 0 and count_encoded > 0:
                # Rough estimate: each symbol occurrence is a replacement
                count += min(count_original, count_encoded)
        return count

    def get_symbol_mapping(self) -> Dict[str, str]:
        """
        Get current encode mapping.

        Returns:
            Copy of encode map
        """
        return self.encode_map.copy()

    def get_common_terms(self, limit: int = 20) -> List[Tuple[str, str, int]]:
        """
        Get most common terms in the map with usage hints.

        Args:
            limit: Maximum number of terms to return

        Returns:
            List of (term, symbol, approximate_length)
        """
        terms = []
        for term, symbol in self.encode_map.items():
            terms.append((term, symbol, len(term)))

        # Sort by term length (longest first) as they save most tokens
        terms.sort(key=lambda x: x[2], reverse=True)
        return terms[:limit]


# Singleton instance for convenience
_default_compressor: Optional[SymbolicCompressor] = None


def get_compressor(symbol_map_path: Optional[Path] = None) -> SymbolicCompressor:
    """
    Get or create default symbolic compressor.

    Args:
        symbol_map_path: Optional custom path to symbol map

    Returns:
        SymbolicCompressor instance
    """
    global _default_compressor
    if _default_compressor is None or symbol_map_path is not None:
        _default_compressor = SymbolicCompressor(symbol_map_path)
    return _default_compressor


def encode_text(text: str, aggressive: bool = False) -> str:
    """
    Convenience function to encode text using default compressor.

    Args:
        text: Text to encode
        aggressive: Aggressive encoding mode

    Returns:
        Encoded text
    """
    compressor = get_compressor()
    return compressor.encode(text, aggressive)


def decode_text(encoded_text: str) -> str:
    """
        Convenience function to decode text using default compressor.

        Args:
            encoded_text: Text with symbols

        Returns:
    :   Decoded text
    """
    compressor = get_compressor()
    return compressor.decode(encoded_text)


def encode_with_stats(
    text: str, aggressive: bool = False
) -> Tuple[str, Dict[str, int]]:
    """
    Convenience function to encode text with statistics.

    Args:
        text: Text to encode
        aggressive: Aggressive encoding mode

    Returns:
        Tuple of (encoded_text, stats)
    """
    compressor = get_compressor()
    return compressor.encode_with_stats(text, aggressive)


if __name__ == "__main__":
    # Simple test/demo

    test_text = """
    neocortex_agent.validate_access with neocortex_security.audit_changes.
    Check neocortex_ledger.get_metrics and neocortex_config.get_config.
    Tools: neocortex_agent, neocortex_akl, neocortex_benchmark.
    """

    print("Testing Symbolic Compressor...")
    print(f"Symbolic map path: {DEFAULT_SYMBOLIC_MAP_PATH}")
    print(f"Exists: {DEFAULT_SYMBOLIC_MAP_PATH.exists()}")

    if DEFAULT_SYMBOLIC_MAP_PATH.exists():
        compressor = SymbolicCompressor()

        print("\n--- Original Text ---")
        print(test_text)

        print("\n--- Encoded (Standard) ---")
        encoded, stats = compressor.encode_with_stats(test_text, aggressive=False)
        print(encoded)
        print(f"\nStats: {json.dumps(stats, indent=2)}")

        print("\n--- Encoded (Aggressive) ---")
        encoded_agg, stats_agg = compressor.encode_with_stats(
            test_text, aggressive=True
        )
        print(encoded_agg)
        print(f"\nStats: {json.dumps(stats_agg, indent=2)}")

        print("\n--- Decoded (from Standard) ---")
        decoded = compressor.decode(encoded)
        print(decoded)

        # Show some common terms
        print("\n--- Top 10 Longest Terms ---")
        for term, symbol, length in compressor.get_common_terms(10):
            print(f"  {term}  {symbol} (saves ~{length - 1} chars per occurrence)")
    else:
        print(
            "ERROR: Symbolic map not found. Run NC-SCR-FR-021-lexicon-extractor.py first."
        )
